### ISSUE TITLE
How to get to and edit the file: "XtremeBS.conf" when I can't find it in the path /data/local/tmp/XtremeBS/

### ISSUE THREAD

**Issue by kozmali** [DethByte64/Xtreme-Battery-Saver#1]
Hi,

I wanted to edit the file: "XtremeBS.conf" but I can't find it in the path: /data/local/tmp/XtremeBS/. I searched for it through FV File Explorer with ROOT rights, directly through Termux or also through ADB and connected mobile to PC.

Can you please upload a video where the "XtremeBS.conf" file is located, or how to find it? Alternatively, how to edit it directly via Termux or when connected to a PC via ADB?

Thank you
Dominik

**Comment by DethByte64** [comment]
First off, you need to have rebooted after installation.

Also you can create a config, in that directory.

**Comment by kozmali** [comment]
Yes I tried that, still the folder is empty: /data/local/ (nothing here)

**Comment by kozmali** [comment]
Can you possibly attach here the default "XtremeBS.conf" file so that I can put it manually in that path?

**Comment by DethByte64** [comment]
you mean there is no tmp/ in /data/local/ ?

**Comment by kozmali** [comment]
Okay, I can see the "XtremeBS.conf" file there, it was enough to use Total Commander and give it ROOT rights to see those files as well. Just to be sure, if someone doesn't see it, I'm also attaching the file here in the thread in the default form (just packet as zip):

[XtremeBS.zip](https://github.com/user-attachments/files/18216361/XtremeBS.zip)

Thank you very much for your quick help DethByte64 :)

**Comment by DethByte64** [comment]
Thank you.
